# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
 #config.vm.network "private_network", ip: "192.168.33.10"

 config.vm.define "cm" do |cm|
  cm.vm.box = "centos/7"
  cm.vm.network "private_network", ip: "192.168.33.11"
  cm.vm.hostname = "cm"
  cm.vm.provision "file", source: "id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
   public_key = File.read("id_rsa.pub")
   config.vm.provision :shell, :inline =>"
     echo 'Copying project local public SSH Keys to the VM'
     mkdir -p /home/vagrant/.ssh
     chmod 700 /home/vagrant/.ssh
     echo '#{public_key}' >> /home/vagrant/.ssh/authorized_keys
     chmod -R 600 /home/vagrant/.ssh/authorized_keys
     echo 'Host 192.168.*.*' >> /home/vagrant/.ssh/config
     echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
     echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
     chmod -R 600 /home/vagrant/.ssh/config
     ", privileged: false
 end

 config.vm.define "jenkins" do |jenkins|
  jenkins.vm.box = "centos/7"
  jenkins.vm.network "private_network", ip: "192.168.33.12"
  jenkins.vm.hostname = "jenkins"
  jenkins.vm.provision "file", source: "id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
   public_key = File.read("id_rsa.pub")
   config.vm.provision :shell, :inline =>"
     echo 'Copying project local public SSH Keys to the VM'
     mkdir -p /home/vagrant/.ssh
     chmod 700 /home/vagrant/.ssh
     echo '#{public_key}' >> /home/vagrant/.ssh/authorized_keys
     chmod -R 600 /home/vagrant/.ssh/authorized_keys
     echo 'Host 192.168.*.*' >> /home/vagrant/.ssh/config
     echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
     echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
     chmod -R 600 /home/vagrant/.ssh/config
     ", privileged: false
 end

end
